- name: Kubernetes no Azure
  href: ./index.yml
- name: Visão geral
- name: Inícios rápidos
  expanded: true
- name: Tutoriais
- name: Conceitos
- name: Guias de instruções
  items:
    - name: Manter os dados com Arquivos do Azure
      href: ../../aks/azure-files-dynamic-pv.md?toc=/azure/container-service/kubernetes/toc.json
    - name: Monitoramento
    - name: Implantar aplicativos Spring Boots
      items:
        - name: Implantar um Aplicativo Spring Boot no Linux no Serviço de Contêiner do Azure
          href: container-service-deploy-spring-boot-app-on-linux.md
        - name: Implantar um Aplicativo Spring Boot em um Cluster Kubernetes no Serviço de Contêiner do Azure
          href: container-service-deploy-spring-boot-app-on-kubernetes.md
        - name: Implantar um aplicativo de inicialização de Spring em contêineres usando o plug-in fabric8 Maven
          href: container-service-deploy-spring-boot-app-using-fabric8-maven-plugin.md
- name: Referência
  items:
    - name: CLI do Azure
      href: /cli/azure/acs
    - name: PowerShell
      href: /powershell/module/az.compute
    - name: REST
      href: /rest/api/container-service
- name: Recursos
  items:
    - name: Roteiro do Azure
      href: 'https://azure.microsoft.com/roadmap/'
    - name: Modelos - Mecanismo do ACS
      href: 'https://github.com/Azure/acs-engine'
    - name: Preços
      href: 'https://azure.microsoft.com/pricing/details/container-service/'
    - name: Disponibilidade de região
      href: 'https://azure.microsoft.com/regions/services/'
    - name: Stack Overflow
      href: 'https://stackoverflow.com/questions/tagged/azure-container-service'
    - name: vídeos
      href: 'https://azure.microsoft.com/resources/videos/index/?services=container-service&sort=newest'