### YamlMime:Landing
title: Kubernetes do Azure Arc (versão prévia)
summary: Aprenda a gerenciar clusters do Kubernetes com o Azure Arc
metadata:
  title: Kubernetes do Azure Arc
  description: Aprenda a gerenciar computadores locais no Azure
  author: 
  ms.service: azure-arc
  ms.topic: landing-page
  ms.date: 06/26/2020
  ms.author: 
  ms.openlocfilehash: a305e50287187292b2a1b9c90b1e6dee98baf75b
  ms.sourcegitcommit: 829d951d5c90442a38012daaf77e86046018e5b9
  ms.translationtype: HT
  ms.contentlocale: pt-BR
  ms.lasthandoff: 10/09/2020
  ms.locfileid: "91824156"
landingContent:
- title: Conectar clusters do Kubernetes ao Azure usando o Azure Arc
  linkLists:
  - linkListType: overview
    links:
    - text: O que é o Kubernetes habilitado para Azure Arc?
      url: overview.md
  - linkListType: quickstart
    links:
    - text: Conectar cluster
      url: connect-cluster.md
  - linkListType: how-to-guide
    links:
    - text: Implantar configurações usando GitOps
      url: use-gitops-connected-cluster.md
    - text: Implantar gráficos do Helm usando GitOps
      url: use-gitops-with-helm.md
    - text: Impor GitOps usando o Azure Policy
      url: use-azure-policy.md
    - text: Implantar cargas de trabalho do Azure IoT Edge
      url: deploy-azure-iot-edge-workloads.md
- title: Arquitetura de referência
  linkLists:
  - linkListType: architecture
    links:
    - text: Gerenciar as implantações e as configurações de clusters híbridos do Kubernetes
      url: /architecture/hybrid/arc-hybrid-kubernetes
